### ISSUE TITLE
Demo app crashed when user enter wrong bank account number

### ISSUE THREAD

**Issue by ominfowave** [andela-Kshittu/Rave#2]
**In response of your API there is no "data" json object but in  your code you are trying to get 'data'!**
```
FATAL EXCEPTION: main
                                                                    Process: flutterwave.com.rave, PID: 8423
                                                                    java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
                                                                        at flutterwave.com.rave.Components.RaveDialog.handleAccountChargeResponse(RaveDialog.java:825)
                                                                        at flutterwave.com.rave.Components.RaveDialog.access$2800(RaveDialog.java:55)
                                                                        at flutterwave.com.rave.Components.RaveDialog$RequestTask.onPostExecute(RaveDialog.java:1001)
                                                                        at flutterwave.com.rave.Components.RaveDialog$RequestTask.onPostExecute(RaveDialog.java:960)
                                                                        at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                                        at android.os.AsyncTask.access$500(AsyncTask.java:180)
                                                                        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5527)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
```

**Comment by kennyshittu** [comment]
@ominfowave Thanks for the detailed report. This is most likely due to changes made to the api response on the server side, without considering existing client impl. I'll look into this ASAP. Thanks.

**Comment by ominfowave** [comment]
Hello, any update on the issue?
